rem run once to copy x_setup.sqf and x_macros.sqf to all directories that need it
copy x_setup.sqf x_init /Y
copy x_setup.sqf x_server /Y
copy x_setup.sqf x_server\x_f /Y
copy x_setup.sqf scripts /Y
copy x_setup.sqf x_client /Y
copy x_setup.sqf x_client\x_f /Y
copy x_setup.sqf x_client\x_f\x_ui /Y
copy x_setup.sqf x_common\x_f /Y
copy x_setup.sqf x_common\x_f\x_net /Y
copy x_setup.sqf x_dlg /Y
copy x_setup.sqf x_missions /Y
copy x_setup.sqf x_missions\ma3a /Y
copy x_setup.sqf x_missions\common /Y
copy x_setup.sqf x_bikb /Y
copy x_setup.sqf IntroAnim /Y
copy x_setup.sqf x_shc /Y
copy x_setup.sqf x_shc\x_f /Y
copy x_macros.sqf x_init /Y
copy x_macros.sqf x_server /Y
copy x_macros.sqf x_server\x_f /Y
copy x_macros.sqf x_client /Y
copy x_macros.sqf x_client\x_f /Y
copy x_macros.sqf x_client\x_f\x_ui /Y
copy x_macros.sqf x_common\x_f /Y
copy x_macros.sqf x_common\x_f\x_net /Y
copy x_macros.sqf scripts /Y
copy x_macros.sqf x_dlg /Y
copy x_macros.sqf x_missions /Y
copy x_macros.sqf x_missions\ma3a /Y
copy x_macros.sqf x_missions\common /Y
copy x_macros.sqf x_bikb /Y
copy x_macros.sqf IntroAnim /Y
copy x_macros.sqf x_shc /Y
copy x_macros.sqf x_shc\x_f /Y
copy xr_macros.sqf x_revive /Y
copy xr_macros.sqf x_revive\xr_f /Y
rem cd ..
